#!/bin/sh -f
#
# A simple script to build robot controllers that make use of the
# libplayerc++ library.

g++ -o $1 `pkg-config --cflags playerc++ --cflags opencv` $1.cpp `pkg-config --libs playerc++ --libs opencv` 